
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone GitHub repository
      uses: actions/checkout@v4
    - name: Download and extract AutoHotKey
      run: |
        Invoke-WebRequest -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip" -OutFile ahk.zip
        Expand-Archive -Path ahk.zip -DestinationPath .\AutoHotKey\ -Force
        Get-ChildItem .\AutoHotKey\Compiler
    - name: Run AutoHotKey compiler to generate binary
      run: |
        powershell.exe .\AutoHotKey\Compiler\Ahk2Exe.exe /in LiveEnhancementSuite.ahk /out "Live Enhancement Suite.exe" /icon resources\blueico.ico
    - name: Install Inno Setup for Installer Creation
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile innosetup.exe
        Start-Process -FilePath ".\innosetup.exe" -ArgumentList "/VERYSILENT","/SUPPRESSMSGBOXES","/SP-","/NORESTART" -Wait
    - name: Run Inno Setup script to generate installer
      run: |
        $InnoSetupCmdLocation="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
        & $InnoSetupCmdLocation /q innoSetupScript.iss
