
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone GitHub repository
      uses: actions/checkout@v4
    - name: Download and extract AutoHotKey
      run: |
        Invoke-WebRequest -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip" -OutFile ahk.zip
        Expand-Archive -Path ahk.zip -DestinationPath .\AutoHotKey\ -Force
        Get-ChildItem .\AutoHotKey\Compiler
    - name: Run AutoHotKey compiler to generate binary
      run: |
        powershell.exe .\AutoHotKey\Compiler\Ahk2Exe.exe /in LiveEnhancementSuite.ahk /out "Live Enhancement Suite.exe" /icon resources\blueico.ico
    - name: Upload compiled executable
      uses: actions/upload-artifact@v4
      with:
        name: Live Enhancement Suite
        path: Live Enhancement Suite.exe
        if-no-files-found: error
